language: node_js
node_js:
  - "4.4.5"
before_script:
  - npm install -g gulp
  - npm install -g bower
  - bower install
script:
  - gulp test:light
deploy:
  provider: heroku
  app: pdes-tips
  api_key:
    secure: $HEROKU_API_KEY
  on:
    all_branches: true
    tags: true
